//------------------------------------------------------------------------------
// <auto-generated>
//     Kode ini dihasilkan oleh tool. Jangan diubah manual.
//     Jika ingin mengubah skema, edit dsLaporanPenjualan.xsd via Visual Studio
//     Dataset Designer, lalu file ini akan di-regenerate otomatis.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Project_Order_Kantin {


    /// <summary>
    /// Strongly-typed DataSet untuk Crystal Report Laporan Penjualan.
    /// </summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsLaporanPenjualan")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsLaporanPenjualan : global::System.Data.DataSet {

        private LaporanPenjualanDataTable tableLaporanPenjualan;

        private global::System.Data.SchemaSerializationMode _schemaSerializationMode =
            global::System.Data.SchemaSerializationMode.IncludeSchema;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsLaporanPenjualan() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler =
                new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsLaporanPenjualan(global::System.Runtime.Serialization.SerializationInfo info,
                                     global::System.Runtime.Serialization.StreamingContext context)
            : base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 =
                    new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) ==
                 global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["LaporanPenjualan"] != null)) {
                    base.Tables.Add(new LaporanPenjualanDataTable(ds.Tables["LaporanPenjualan"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler =
                new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }

        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(
            global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public LaporanPenjualanDataTable LaporanPenjualan {
            get {
                return this.tableLaporanPenjualan;
            }
        }

        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(
            global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get { return this._schemaSerializationMode; }
            set { this._schemaSerializationMode = value; }
        }

        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(
            global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get { return base.Tables; }
        }

        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(
            global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get { return base.Relations; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsLaporanPenjualan cln = ((dsLaporanPenjualan)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() { return false; }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() { return false; }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) ==
                 global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["LaporanPenjualan"] != null)) {
                    base.Tables.Add(new LaporanPenjualanDataTable(ds.Tables["LaporanPenjualan"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() { this.InitVars(true); }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableLaporanPenjualan = ((LaporanPenjualanDataTable)(base.Tables["LaporanPenjualan"]));
            if ((initTable == true)) {
                if ((this.tableLaporanPenjualan != null)) {
                    this.tableLaporanPenjualan.InitVars();
                }
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsLaporanPenjualan";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsLaporanPenjualan.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableLaporanPenjualan = new LaporanPenjualanDataTable();
            base.Tables.Add(this.tableLaporanPenjualan);
        }

        private bool ShouldSerializeLaporanPenjualan() { return false; }

        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) { this.InitVars(); }
        }

        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(
            global::System.Xml.Schema.XmlSchemaSet xs) {
            dsLaporanPenjualan ds = new dsLaporanPenjualan();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace) == false) {
                xs.Add(dsSchema);
            }
            return type;
        }

        public delegate void LaporanPenjualanRowChangeEventHandler(object sender,
            LaporanPenjualanRowChangeEvent e);

        // =================================================================
        //   DataTable : LaporanPenjualan
        // =================================================================
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class LaporanPenjualanDataTable : global::System.Data.TypedTableBase<LaporanPenjualanRow> {

            private global::System.Data.DataColumn columnOrderItemId;
            private global::System.Data.DataColumn columnOrderId;
            private global::System.Data.DataColumn columnOrderNumber;
            private global::System.Data.DataColumn columnTanggal;
            private global::System.Data.DataColumn columnNamaItem;
            private global::System.Data.DataColumn columnKategori;
            private global::System.Data.DataColumn columnHargaSatuan;
            private global::System.Data.DataColumn columnJumlah;
            private global::System.Data.DataColumn columnSubtotal;
            private global::System.Data.DataColumn columnMetodePembayaran;
            private global::System.Data.DataColumn columnStatus;

            public LaporanPenjualanDataTable() {
                this.TableName = "LaporanPenjualan";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }

            internal LaporanPenjualanDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }

            protected LaporanPenjualanDataTable(global::System.Runtime.Serialization.SerializationInfo info,
                                                global::System.Runtime.Serialization.StreamingContext context)
                : base(info, context) {
                this.InitVars();
            }

            public global::System.Data.DataColumn OrderItemIdColumn { get { return this.columnOrderItemId; } }
            public global::System.Data.DataColumn OrderIdColumn { get { return this.columnOrderId; } }
            public global::System.Data.DataColumn OrderNumberColumn { get { return this.columnOrderNumber; } }
            public global::System.Data.DataColumn TanggalColumn { get { return this.columnTanggal; } }
            public global::System.Data.DataColumn NamaItemColumn { get { return this.columnNamaItem; } }
            public global::System.Data.DataColumn KategoriColumn { get { return this.columnKategori; } }
            public global::System.Data.DataColumn HargaSatuanColumn { get { return this.columnHargaSatuan; } }
            public global::System.Data.DataColumn JumlahColumn { get { return this.columnJumlah; } }
            public global::System.Data.DataColumn SubtotalColumn { get { return this.columnSubtotal; } }
            public global::System.Data.DataColumn MetodePembayaranColumn { get { return this.columnMetodePembayaran; } }
            public global::System.Data.DataColumn StatusColumn { get { return this.columnStatus; } }

            [global::System.ComponentModel.Browsable(false)]
            public int Count { get { return this.Rows.Count; } }

            public LaporanPenjualanRow this[int index] {
                get { return ((LaporanPenjualanRow)(this.Rows[index])); }
            }

            public event LaporanPenjualanRowChangeEventHandler LaporanPenjualanRowChanging;
            public event LaporanPenjualanRowChangeEventHandler LaporanPenjualanRowChanged;
            public event LaporanPenjualanRowChangeEventHandler LaporanPenjualanRowDeleting;
            public event LaporanPenjualanRowChangeEventHandler LaporanPenjualanRowDeleted;

            public void AddLaporanPenjualanRow(LaporanPenjualanRow row) { this.Rows.Add(row); }

            public override global::System.Data.DataTable Clone() {
                LaporanPenjualanDataTable cln = ((LaporanPenjualanDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }

            protected override global::System.Data.DataTable CreateInstance() {
                return new LaporanPenjualanDataTable();
            }

            internal void InitVars() {
                this.columnOrderItemId = base.Columns["OrderItemId"];
                this.columnOrderId = base.Columns["OrderId"];
                this.columnOrderNumber = base.Columns["OrderNumber"];
                this.columnTanggal = base.Columns["Tanggal"];
                this.columnNamaItem = base.Columns["NamaItem"];
                this.columnKategori = base.Columns["Kategori"];
                this.columnHargaSatuan = base.Columns["HargaSatuan"];
                this.columnJumlah = base.Columns["Jumlah"];
                this.columnSubtotal = base.Columns["Subtotal"];
                this.columnMetodePembayaran = base.Columns["MetodePembayaran"];
                this.columnStatus = base.Columns["Status"];
            }

            private void InitClass() {
                this.columnOrderItemId = new global::System.Data.DataColumn(
                    "OrderItemId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrderItemId);

                this.columnOrderId = new global::System.Data.DataColumn(
                    "OrderId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrderId);

                this.columnOrderNumber = new global::System.Data.DataColumn(
                    "OrderNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrderNumber);

                this.columnTanggal = new global::System.Data.DataColumn(
                    "Tanggal", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTanggal);

                this.columnNamaItem = new global::System.Data.DataColumn(
                    "NamaItem", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNamaItem);

                this.columnKategori = new global::System.Data.DataColumn(
                    "Kategori", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKategori);

                this.columnHargaSatuan = new global::System.Data.DataColumn(
                    "HargaSatuan", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHargaSatuan);

                this.columnJumlah = new global::System.Data.DataColumn(
                    "Jumlah", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJumlah);

                this.columnSubtotal = new global::System.Data.DataColumn(
                    "Subtotal", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSubtotal);

                this.columnMetodePembayaran = new global::System.Data.DataColumn(
                    "MetodePembayaran", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMetodePembayaran);

                this.columnStatus = new global::System.Data.DataColumn(
                    "Status", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStatus);
            }

            public LaporanPenjualanRow NewLaporanPenjualanRow() {
                return ((LaporanPenjualanRow)(this.NewRow()));
            }

            protected override global::System.Data.DataRow NewRowFromBuilder(
                global::System.Data.DataRowBuilder builder) {
                return new LaporanPenjualanRow(builder);
            }

            protected override global::System.Type GetRowType() { return typeof(LaporanPenjualanRow); }

            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.LaporanPenjualanRowChanged != null)) {
                    this.LaporanPenjualanRowChanged(this,
                        new LaporanPenjualanRowChangeEvent(((LaporanPenjualanRow)(e.Row)), e.Action));
                }
            }

            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.LaporanPenjualanRowChanging != null)) {
                    this.LaporanPenjualanRowChanging(this,
                        new LaporanPenjualanRowChangeEvent(((LaporanPenjualanRow)(e.Row)), e.Action));
                }
            }

            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.LaporanPenjualanRowDeleted != null)) {
                    this.LaporanPenjualanRowDeleted(this,
                        new LaporanPenjualanRowChangeEvent(((LaporanPenjualanRow)(e.Row)), e.Action));
                }
            }

            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.LaporanPenjualanRowDeleting != null)) {
                    this.LaporanPenjualanRowDeleting(this,
                        new LaporanPenjualanRowChangeEvent(((LaporanPenjualanRow)(e.Row)), e.Action));
                }
            }

            public void RemoveLaporanPenjualanRow(LaporanPenjualanRow row) { this.Rows.Remove(row); }

            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(
                global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type =
                    new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence =
                    new global::System.Xml.Schema.XmlSchemaSequence();
                dsLaporanPenjualan ds = new dsLaporanPenjualan();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 =
                    new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 =
                    new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "LaporanPenjualanDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace) == false) {
                    xs.Add(dsSchema);
                }
                return type;
            }
        }

        // =================================================================
        //   DataRow : LaporanPenjualanRow
        // =================================================================
        public partial class LaporanPenjualanRow : global::System.Data.DataRow {

            private LaporanPenjualanDataTable tableLaporanPenjualan;

            internal LaporanPenjualanRow(global::System.Data.DataRowBuilder rb) : base(rb) {
                this.tableLaporanPenjualan = ((LaporanPenjualanDataTable)(this.Table));
            }

            public int OrderItemId {
                get {
                    try { return ((int)(this[this.tableLaporanPenjualan.OrderItemIdColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom OrderItemId.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.OrderItemIdColumn] = value; }
            }

            public int OrderId {
                get {
                    try { return ((int)(this[this.tableLaporanPenjualan.OrderIdColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom OrderId.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.OrderIdColumn] = value; }
            }

            public string OrderNumber {
                get {
                    try { return ((string)(this[this.tableLaporanPenjualan.OrderNumberColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom OrderNumber.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.OrderNumberColumn] = value; }
            }

            public global::System.DateTime Tanggal {
                get {
                    try { return ((global::System.DateTime)(this[this.tableLaporanPenjualan.TanggalColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom Tanggal.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.TanggalColumn] = value; }
            }

            public string NamaItem {
                get {
                    try { return ((string)(this[this.tableLaporanPenjualan.NamaItemColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom NamaItem.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.NamaItemColumn] = value; }
            }

            public string Kategori {
                get {
                    try { return ((string)(this[this.tableLaporanPenjualan.KategoriColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom Kategori.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.KategoriColumn] = value; }
            }

            public int HargaSatuan {
                get {
                    try { return ((int)(this[this.tableLaporanPenjualan.HargaSatuanColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom HargaSatuan.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.HargaSatuanColumn] = value; }
            }

            public int Jumlah {
                get {
                    try { return ((int)(this[this.tableLaporanPenjualan.JumlahColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom Jumlah.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.JumlahColumn] = value; }
            }

            public int Subtotal {
                get {
                    try { return ((int)(this[this.tableLaporanPenjualan.SubtotalColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom Subtotal.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.SubtotalColumn] = value; }
            }

            public string MetodePembayaran {
                get {
                    try { return ((string)(this[this.tableLaporanPenjualan.MetodePembayaranColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom MetodePembayaran.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.MetodePembayaranColumn] = value; }
            }

            public string Status {
                get {
                    try { return ((string)(this[this.tableLaporanPenjualan.StatusColumn])); }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException(
                            "Nilai NULL pada kolom Status.", e);
                    }
                }
                set { this[this.tableLaporanPenjualan.StatusColumn] = value; }
            }
        }

        // =================================================================
        //   Event Args
        // =================================================================
        public class LaporanPenjualanRowChangeEvent : global::System.EventArgs {
            private LaporanPenjualanRow eventRow;
            private global::System.Data.DataRowAction eventAction;

            public LaporanPenjualanRowChangeEvent(LaporanPenjualanRow row,
                global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }

            public LaporanPenjualanRow Row { get { return this.eventRow; } }
            public global::System.Data.DataRowAction Action { get { return this.eventAction; } }
        }
    }
}

#pragma warning restore 1591
